# Generated by Django 5.1.3 on 2024-11-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('users', '0011_user_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.ManyToManyField(to='comments.comment'),
        ),
    ]
