# Generated by Django 5.1.3 on 2024-11-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_rename_comment_text_commenthistory_comment'),
        ('projects', '0015_alter_projecthistory_project_and_more'),
        ('tasks', '0007_task_comment_history_alter_task_comments'),
        ('users', '0012_user_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comments',
            field=models.ManyToManyField(blank=True, to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(blank=True, through='projects.ProjectUser', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='tasks.task'),
        ),
    ]
