# Generated by Django 5.1.3 on 2024-11-21 13:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_is_active'),
        ('users', '0002_alter_user_managers_alter_user_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersProjects',
            new_name='ProjectUser',
        ),
    ]
