# Generated by Django 5.1.3 on 2024-11-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projecthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
