# Generated by Django 5.1.3 on 2024-11-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_status'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(related_name='tasks', to='tasks.task'),
        ),
    ]
