# Generated by Django 5.1.3 on 2024-11-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_tasks'),
        ('tasks', '0005_remove_task_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='project_tasks', to='tasks.task'),
        ),
    ]
