# Generated by Django 5.1.3 on 2024-11-25 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_commenthistory_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commenthistory',
            old_name='comment_text',
            new_name='comment',
        ),
    ]
