# Generated by Django 5.1.3 on 2024-11-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='last_update',
        ),
    ]
