# Generated by Django 5.1.3 on 2024-11-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('tasks', '0005_remove_task_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to='comments.comment'),
        ),
    ]
